config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web => '/sidekiq' if defined?(Sidekiq)

  root 'dashboard#index'

  get 'up' => 'rails/health#show'

  devise_for :users,
             path: '/', only: %i[sessions passwords omniauth_callbacks],
             controllers: begin
               options = { sessions: 'sessions', passwords: 'passwords' }
               options[:omniauth_callbacks] = 'omniauth_callbacks' if User.devise_modules.include?(:omniauthable)
               options
             end

  devise_scope :user do
    if Docuseal.multitenant?
      resource :registration, only: %i[show], path: 'sign_up'
      unauthenticated do
        resource :registration, only: %i[create], path: 'new' do
          get '' => :new, as: :new
        end
      end
    end

    resource :invitation, only: %i[update] do
      get '' => :edit
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :attachments, only: %i[create]
    resources :submitters_autocomplete, only: %i[index]
    resources :template_folders_autocomplete, only: %i[index]
    resources :submitter_email_clicks, only: %i[create]
    resources :submitter_form_views, only: %i[create]
    resources :submitters, only: %i[index show update]
    resources :submissions, only: %i[index show create destroy] do
      collection do
        resources :emails, only: %i[create], controller: 'submissions', as: :submissions_emails
      end
    end
    resources :templates, only: %i[update show index destroy] do
      resources :clone, only: %i[create], controller: 'templates_clone'
      resources :submissions, only: %i[index create]
      resources :documents, only: %i[create], controller: 'templates_documents'
    end
  end

  resources :verify_pdf_signature, only: %i[create]
  resource :mfa_setup, only: %i[show new edit create destroy], controller: 'mfa_setup'
  resources :account_configs, only: %i[create]
  resources :timestamp_server, only: %i[create]
  resources :dashboard, only: %i[index]
  resources :setup, only: %i[index create]
  resource :newsletter, only: %i[show update]
  resources :enquiries, only: %i[create]
  resources :users, only: %i[new create edit update destroy]
  resource :user_signature, only: %i[edit update destroy]
  resources :submissions, only: %i[show destroy]
  resources :console_redirect, only: %i[index]
  resource :templates_upload, only: %i[create]
  authenticated do
    resource :templates_upload, only: %i[show], path: 'new'
  end
  resources :templates_archived, only: %i[index], path: 'archived'
  resources :folders, only: %i[show edit update destroy], controller: 'template_folders'
  resources :templates, only: %i[new create edit show destroy] do
    resources :restore, only: %i[create], controller: 'templates_restore'
    resources :archived, only: %i[index], controller: 'templates_archived_submissions'
    resources :submissions, only: %i[new create]
    resource :folder, only: %i[edit update], controller: 'templates_folders'
    resources :submissions_export, only: %i[index new]
  end
  resources :preview_document_page, only: %i[show], path: '/preview/:attachment_uuid'

  resources :start_form, only: %i[show update], path: 'd', param: 'slug' do
    get :completed
  end

  resources :submit_form, only: %i[show update], path: 's', param: 'slug' do
    get :completed
  end

  resources :submissions_preview, only: %i[show], path: 'e', param: 'slug'

  resources :send_submission_email, only: %i[create] do
    get :success, on: :collection
  end

  resources :submitters, only: %i[], param: 'slug' do
    resources :download, only: %i[index], controller: 'submissions_download'
    resources :send_email, only: %i[create], controller: 'submitters_send_email'
    resources :debug, only: %i[index], controller: 'submissions_debug' if Rails.env.development?
  end

  scope '/settings', as: :settings do
    unless Docuseal.multitenant?
      resources :storage, only: %i[index create], controller: 'storage_settings'
      resources :email, only: %i[index create], controller: 'email_smtp_settings'
      resources :sms, only: %i[index], controller: 'sms_settings'
      resources :sso, only: %i[index], controller: 'sso_settings'
    end
    resources :notifications, only: %i[index create], controller: 'notifications_settings'
    resource :esign, only: %i[show create new update destroy], controller: 'esign_settings'
    resources :users, only: %i[index]
    resource :personalization, only: %i[show create], controller: 'personalization_settings'
    if !Docuseal.multitenant? || Docuseal.demo?
      resources :api, only: %i[index create], controller: 'api_settings'
      resource :webhooks, only: %i[show create update], controller: 'webhook_settings'
    end
    resource :account, only: %i[show update]
    resources :profile, only: %i[index] do
      collection do
        patch :update_contact
        patch :update_password
        patch :update_app_url
      end
    end
  end

  ActiveSupport.run_load_hooks(:routes, self)
end

app/controllers/start_form_controller.rb
# frozen_string_literal: true

class StartFormController < ApplicationController
  layout 'form'

  skip_before_action :authenticate_user!
  skip_authorization_check

  before_action :load_template

  def show
    @submitter = @template.submissions.new.submitters.new(uuid: @template.submitters.first['uuid'])
  end

  def update
    @submitter = Submitter.where(submission: @template.submissions.where(archived_at: nil))
                          .order(id: :desc)
                          .then { |rel| params[:resubmit].present? ? rel.where(completed_at: nil) : rel }
                          .find_or_initialize_by(**submitter_params.compact_blank)

    if @submitter.completed_at?
      redirect_to start_form_completed_path(@template.slug, email: submitter_params[:email])
    else
      if @template.submitters.to_a.size > 1 && @submitter.new_record?
        @error_message = 'Not found'

        return render :show
      end

      assign_submission_attributes(@submitter, @template) if @submitter.new_record?

      if @submitter.save
        redirect_to submit_form_path(@submitter.slug)
      else
        render :show
      end
    end
  end

  def completed
    @submitter = Submitter.where(submission: @template.submissions)
                          .where.not(completed_at: nil)
                          .find_by!(email: params[:email])
  end

  private

  def assign_submission_attributes(submitter, template)
    resubmit_submitter =
      if params[:resubmit].present?
        Submitter.where(submission: @template.submissions).find_by(slug: params[:resubmit])
      end

    submitter.assign_attributes(
      uuid: template.submitters.first['uuid'],
      ip: request.remote_ip,
      ua: request.user_agent,
      values: resubmit_submitter&.preferences&.fetch('default_values', nil) || {},
      preferences: resubmit_submitter&.preferences.presence || { 'send_email' => true }
    )

    if submitter.values.present?
      resubmit_submitter.attachments.each do |attachment|
        submitter.attachments << attachment.dup if submitter.values.value?(attachment.uuid)
      end
    end

    submitter.submission ||= Submission.new(template:,
                                            template_submitters: template.submitters,
                                            source: :link)

    submitter
  end

  def submitter_params
    params.require(:submitter).permit(:email, :phone, :name).tap do |attrs|
      attrs[:email] = Submissions.normalize_email(attrs[:email])
    end
  end

  def load_template
    slug = params[:slug] || params[:start_form_slug]

    @template = Template.find_by!(slug:)
  end
end

app/views/start_form/_banner.html.erb
<%= render 'docuseal_logo' %>

app/views/start_form/_docuseal_logo.html.erb
<a href="/" class="flex justify-center items-center">
  <span class="mr-3">
    <%= render 'shared/logo', width: '50px', height: '50px' %>
  </span>
  <h1 class="text-5xl font-bold text-center">DocuSeal</h1>
</a>

app/views/start_form/completed.html.erb
<div class="max-w-md mx-auto px-2 mt-12 mb-4">
  <div class="space-y-6 mx-auto">
    <div class="space-y-6">
      <div class="flex items-center justify-center">
        <%= render 'banner' %>
      </div>
      <div class="flex items-center bg-base-200 rounded-xl p-4 mb-4">
        <div class="flex items-center">
          <div class="mr-3">
            <%= svg_icon('writing_sign', class: 'w-10 h-10') %>
          </div>
          <div>
            <p class="text-lg font-bold mb-1"><%= @submitter.submission.template.name %></p>
            <p class="text-sm">Signed on <%= l(@submitter.completed_at.to_date, format: :long, locale: @submitter.submission.template.account.locale) %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center text-2xl font-semibold">
      Form has been submitted already
    </div>
    <% if Accounts.can_send_emails?(@submitter.submission.template.account) %>
      <div>
        <%= button_to button_title(title: 'Send copy to Email', disabled_with: 'Sending', icon: svg_icon('mail_forward', class: 'w-6 h-6')), send_submission_email_index_path, params: { submitter_slug: @submitter.slug }, form: { onsubmit: 'event.submitter.disabled = true' }, class: 'base-button w-full' %>
      </div>
    <% end %>
    <% if @template.submitters.to_a.size == 1 %>
      <div>
        <%= button_to button_title(title: 'Resubmit', disabled_with: 'Resubmit', icon: svg_icon('reload', class: 'w-6 h-6')), start_form_path(@template.slug), params: { submitter: { email: params[:email] }, resubmit: @submitter.slug }, method: :put, form: { onsubmit: 'event.submitter.disabled = true' }, class: 'white-button w-full' %>
      </div>
    <% end %>
  </div>
</div>
<%= render 'shared/attribution', link_path: '/start' %>

app/views/start_form/show.html.erb
<div class="max-w-md mx-auto px-2 mt-12 mb-4">
  <div class="space-y-6 mx-auto">
    <div class="space-y-6">
      <div class="text-center w-full space-y-6">
        <%= render 'banner' %>
        <% unless @template.archived_at? %>
          <p class="text-xl font-semibold text-center">You have been invited to submit a form</p>
        <% end %>
      </div>
      <div class="flex items-center bg-base-200 rounded-xl p-4 mb-4">
        <div class="flex items-center">
          <div class="mr-3">
            <%= svg_icon('writing_sign', class: 'w-10 h-10') %>
          </div>
          <div>
            <p class="text-lg font-bold mb-1"><%= @template.name %></p>
            <% if @template.archived_at? %>
              <p class="text-sm">Form has been deleted by <span class="font-semibold"><%= @template.account.name %></span>.</p>
            <% else %>
              <p class="text-sm">Invited by <span class="font-semibold"><%= @template.account.name %></span></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% unless @template.archived_at? %>
      <%= form_for @submitter, url: start_form_path(@template.slug), data: { turbo_frame: :_top }, method: :put, html: { class: 'space-y-4', onsubmit: 'event.submitter.disabled = true' } do |f| %>
        <div class="form-control !mt-0">
          <%= f.label :email, class: 'label' %>
          <%= f.email_field :email, value: current_user&.email || params[:email] || @submitter.email, required: true, class: 'base-input', placeholder: 'Provide your email to start' %>
          <%= @error_message %>
        </div>
        <div class="form-control">
          <%= f.button button_title(title: 'Start', disabled_with: 'Starting'), class: 'base-button' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= render 'shared/attribution', link_path: '/start' %>